local repo = "https://raw.githubusercontent.com/mapplegaming208/Obsidian/main/"
local Library = loadstring(game:HttpGet(repo .. "Library.lua"))()
local ThemeManager = loadstring(game:HttpGet(repo .. "addons/ThemeManager.lua"))()
local SaveManager = loadstring(game:HttpGet(repo .. "addons/SaveManager.lua"))()

local Options = Library.Options
local Toggles = Library.Toggles

Library.ForceCheckbox = false
Library.ShowToggleFrameInKeybinds = true

local sigma = Library:CreateWindow({
    Title = "unsilencedhub v1",
    Footer = "version: mid-sep",
    Icon = nil,
    NotifySide = "Right",
    Center = "true"
})
Library:Notify("loaded", 4, 7695856187) -- tada notif sound
if game.PlaceId == 
--end
Library:Notify("thanks for using this amazing script by some guy on github", 4, 7695983456) -- old android notification sound
